### ISSUE TITLE
Поправить Readme

### ISSUE THREAD

**Issue by kopylovvlad** [rambler-digital-solutions/danger-spec_postfix#3]
Мне кажется что readme немного противоречит реализации.

Ридми https://github.com/rambler-digital-solutions/danger-spec_postfix/blame/main/README.md#L3

Реализация https://github.com/rambler-digital-solutions/danger-spec_postfix/blob/main/lib/spec_postfix/plugin.rb#L4

**Comment by peresvetjke** [comment]
Спасибо!

Поправил, ревью плс: https://github.com/rambler-digital-solutions/danger-spec_postfix/pull/4

**Comment by peresvetjke** [comment]
Решено в рамках https://github.com/rambler-digital-solutions/danger-spec_postfix/pull/4
